sendsmaily/smaily-opencart-module

opencart 1.5.6.4/upload/catalog/view/theme/default/template/module/smaily_for_opencart.tpl
Optin form's name input didn't have the same style as email input.
Changed the input type from 'text to 'name' so it looks like the same now.
=> Changed name input type

opencart 3.0.0.0 - 3.0.3.1/upload/admin/controller/extension/module/smaily_for_opencart.php, opencart 3.0.0.0 - 3.0.3.1/upload/admin/language/en-gb/extension/module/smaily_for_opencart.php
Changed way website URL is retrieved from config.
On a fresh opencart install, the config_url would return null
Now it retrieves the admin page URL and removes /admin/ from it.
=> Fixed not displaying full site URL for CRON links.

opencart 2.2.0.0/upload/catalog/controller/smailyforopencart/cron_customers.php, opencart 2.3.0.0 - 2.3.0.2/upload/catalog/controller/extension/smailyforopencart/cron_customers.php, opencart 3.0.0.0 - 3.0.3.1/upload/catalog/controller/extension/smailyforopencart/cron_customers.php
Previously customer sync time was saved when cron was finished.
This could cause issues when cron takes a long time and some customers are added/modified in the meantime.
Currently, it will get a pointer with the time before starting cron and save that time to settings after cron finishes.
=> Save customer sync cron time before finished

opencart 1.5.6.4/Dockerfile, opencart 1.5.6.4/docker-compose.yml, opencart 2.2.0.0/Dockerfile, opencart 2.2.0.0/docker-compose.yml, opencart 2.3.0.0 - 2.3.0.2/Dockerfile, opencart 2.3.0.0 - 2.3.0.2/docker-compose.yml, opencart 3.0.0.0 - 3.0.3.1/Dockerfile, opencart 3.0.0.0 - 3.0.3.1/docker-compose.yml
Docker support for a fast and easy development environment
Using PHP:7.3-apache on OpenCart 3 and 2.3
Older OpenCart versions behave unexpectedly with newer PHP versions
=> Add Docker and docker-compose files

opencart 1.5.6.4/Dockerfile, opencart 1.5.6.4/docker-compose.yml, opencart 2.2.0.0/Dockerfile, opencart 2.2.0.0/docker-compose.yml, opencart 2.3.0.0 - 2.3.0.2/Dockerfile, opencart 2.3.0.0 - 2.3.0.2/docker-compose.yml, opencart 3.0.0.0 - 3.0.3.1/Dockerfile, opencart 3.0.0.0 - 3.0.3.1/docker-compose.yml
Renamed `examplepass` to `smaily1` to be consistent
Added a sed script to fill out the password and e-mail inputs.
Would've used testing@smaily.sandbox instead of testing@smaily.sb but OpenCart detected it as invalid.
Tested all versions. Ready for review
=> Make Docker's OpenCart installation more user friendly

opencart 1.5.6.4/Dockerfile, opencart 1.5.6.4/docker-compose.yml, opencart 1.5.6.4/entrypoint.sh, opencart 1.5.6.4/modman-wrapper.sh, opencart 2.2.0.0/Dockerfile, opencart 2.2.0.0/docker-compose.yml, opencart 2.2.0.0/entrypoint.sh, opencart 2.2.0.0/modman-wrapper.sh, opencart 2.3.0.0 - 2.3.0.2/Dockerfile, opencart 2.3.0.0 - 2.3.0.2/docker-compose.yml, opencart 2.3.0.0 - 2.3.0.2/entrypoint.sh, opencart 2.3.0.0 - 2.3.0.2/modman-wrapper.sh, opencart 3.0.0.0 - 3.0.3.1/Dockerfile, opencart 3.0.0.0 - 3.0.3.1/docker-compose.yml, opencart 3.0.0.0 - 3.0.3.1/entrypoint.sh, opencart 3.0.0.0 - 3.0.3.1/modman-wrapper.sh
Replace data prefilling with sed in favor of the CLI installer.
Still needs work on 1.5.6.4
=> Use CLI installer for OpenCart install

docker-compose.yaml
This is to avoid issues with running multiple OpenCart installations from the same local Git repository.
=> Add suffix to development environment volumes

.github/workflows/release.yaml
Workflow builds a zip file and adds it to a release.
Release tags should be formatted as `2.2.x-1.2.0`.
=> Add workflow to generate a zip file

CHANGELOG.md, install.xml, upload/admin/controller/extension/module/smaily_for_opencart.php, upload/catalog/model/extension/smailyforopencart/helper.php
Customer cron `sync_time` is now initialized when saving settings on the admin page. Also, previous `sync_time` is not discarded when saving settings on the admin page.
Fixes #57
=> Fix customer cron sync time not being updated

CHANGELOG.md, install.xml, upload/admin/controller/extension/module/smaily_for_opencart.php
Fixes #61 
Currently, credentials posted that were URL escaped didn't get encoded and caused validation to fail. This pull-request fixes this issue by first decoding posted fields and then validating with decoded values.
=> Fix valid credentials not accepted

.github/workflows/release.yaml
Added a workflow file for branch 1.5.x also.
For version 1.5.x there is no feature to install our module from `ocmod.zip` file but to keep branches consistent I would add the same option to download the plugins files from the releases page.
Also when releasing to OpenCart it makes it easier to just download a zip from the releases page and upload it to their marketplace. Also less error-prone solution than manually selecting files and compressing.
=> Add workflow to create a zip file

.github/pull_request_template.md
Use platform version tag instead of defining it in the pull request description for better pull requests filtering experience in GitHub.
=> Update release pull request template

upload/admin/controller/extension/module/smaily_for_opencart.php
for #125
tried getting plugin version from install.xml but realized that file can't be accessed if plugin was manually installed.
searched the sql database and the plugin version isn't stored anywhere, no chance querying it from some table.
created a variable and appended it to the heading title, this has to be updated as new versions are released.
=> Display module version

Dockerfile, README.md
Tested out newer versions (3.0.3.1+) and found no issues with our plugin. Releases mainly dealt with adding/removing extensions.
Although newer OpenCart versions (since 3.0.3.5) now require PHP 7.3 as a minimum, added it to README
for #110
=> Bump OC versions

upload/catalog/controller/extension/smailyforopencart/cron_customers.php
Things I noticed developing 2.3.x
- Instead of using $list, $subscirbers array is sent towards Smaily API endpoint. This sends all fields attributed to the customer in a request. We should only send fields the customer has enabled in settings. 
- unsubscribeCustomers() function was deleted, which forgoes setting newsletter to '0' in local store DB
- $response variable was deleted in try/catch block. This leaves only one declaration of $response, "no customers to sync". Which is then printed to the log after running customer sync.
=> Fix mistakes introduced by refactoring to Request class

upload/admin/controller/extension/module/smaily_for_opencart.php, upload/catalog/controller/extension/smailyforopencart/cron_cart.php, upload/catalog/controller/extension/smailyforopencart/cron_customers.php
this
```
} catch (SmailyError $error) {
$msg = $error->getMessage();
$this->log->write($msg);
echo($msg);
```
prints out _GET/POST request to Smaily API_ but should print _Smaily API Error: %s. API code: %d;_
=> Use error handling for requests like used in 1.5.x

upload/catalog/model/smailyforopencart/helper.php
it would load all customers emails into an array and then unsubscribe them x amount of times, x being the length of customers email divided by chunk limit (500), i.e 2000 emails/500 limiter runs an SQL query to unsubscribe 2000 customers from DB four times repeatedly.
=> Fix unsubscribing in chunks not working in chunks

CHANGELOG.md, README.md
Abandoned cart page was merged into 1.5.0 some time ago, forgot to write about it for the release.
Added it to changelog and wrote a readme section for it
=> Include abandoned cart page documentation in 1.5.0 for for 2.2.x

CHANGELOG.md, README.md
Abandoned Cart page is a new feature in 1.5.0 but lacks documentation in readme and changelog. Added the appropriate info to both
=> Include abandoned cart page documentation in 1.5.0 for for 3.0.x

CHANGELOG.md, README.md
Add abandoned cart admin page documentation to changelog and readme. The feature is included in the coming release of 1.5.0
=> Include abandoned cart page documentation in 1.5.0 for for 2.3.x

upload/admin/view/stylesheet/abandoned_carts_table.css, upload/admin/view/stylesheet/smaily_oc.css, upload/admin/view/template/module/smaily_for_opencart.tpl, upload/modman
If the shopping cart is very big, the table contents will be directly at the center, even when table cells have been stretched wide. 
The stylesheet aligns it to the top.
=> Stylesheet for abandoned carts table wasn't added

CHANGELOG.md
Sorry again. I wrongly remembered I added `html_entity_decode` to RSS for 2.2.x like it was in 3.0.x, but this is not correct.
=> Release 1.5.1 for 2.2.x cointains incorrect item in changelog.md 

upload/admin/controller/extension/module/smaily_for_opencart.php
Adding parenthesis, the expression doesn't evaluate the rest of the statement if the RSS limit is not set. Previously if the RSS limit was not set it would still evaluate the range of 1-250, prompting an undefined index error.
Fix for issue #190
=> Add paranthesis to if statement when checking if RSS limit is in range

upload/admin/controller/extension/module/smaily_for_opencart.php
Input fields are prefixed with `module_` in 3.0.x but RSS product limit was not using that prefix and this resulted in an undefined index error.
Related to issue #190
=> RSS product limit was using wrong index

upload/admin/controller/extension/module/smaily_for_opencart.php
Previously error was only shown when the limit was below 1.
=> RSS limit expression requires parentheses 

upload/admin/controller/module/smaily_for_opencart.php
Previously it would only pop an error if value was below 1.
=> RSS product limit expression requires parentheses

CHANGELOG.md, install.xml, upload/admin/controller/extension/module/smaily_for_opencart.php
**Version changelog**
- Fix undefined index error for RSS product limit - [[#190](https://github.com/sendsmaily/smaily-opencart-module/issues/190)]
- Fix validation error not showing if RSS product limit higher than 250 - [[#193](https://github.com/sendsmaily/smaily-opencart-module/pull/193)]
**Release checklist**
**After PR merge**
=> Release 1.5.2 for 3.0.x

CHANGELOG.md, install.xml, upload/admin/controller/extension/module/smaily_for_opencart.php
**Version changelog**
A list of changes regarding the next version release:
- Fix validation error not showing if RSS product limit higher than 250 - [[#194](https://github.com/sendsmaily/smaily-opencart-module/pull/194)]
**Release checklist**
**After PR merge**
=> Release 1.5.2 for 2.3.x
