sendsmaily/smaily-opencart-module

- .gitignore
- opencart 1.5.6.4/upload/admin/controller/module/smaily_for_opencart.php
- opencart 1.5.6.4/upload/admin/language/english/module/smaily_for_opencart.php
- opencart 1.5.6.4/upload/admin/model/smailyforopencart/admin.php
- opencart 1.5.6.4/upload/admin/view/template/module/smaily_for_opencart.tpl
- opencart 1.5.6.4/upload/catalog/controller/smailyforopencart/cron_customers.php
- opencart 1.5.6.4/upload/catalog/model/smailyforopencart/helper.php
> Customer Sync saving function and settings tab

- opencart 1.5.6.4/upload/admin/view/template/module/smaily_for_opencart.tpl
When user is validated, it will show the customer sync settings tab.
Jquery checks if username has been filled and uses .trigger('click') to activate the customer sync tab
> Default open Customer Sync settings when validated

- .gitignore
- opencart 1.5.6.4/installation.txt
- opencart 1.5.6.4/upload/admin/controller/module/smaily_for_opencart.php
- opencart 1.5.6.4/upload/admin/language/english/module/smaily_for_opencart.php
- opencart 1.5.6.4/upload/admin/model/smailyforopencart/admin.php
- opencart 1.5.6.4/upload/admin/view/template/module/smaily_for_opencart.tpl
- opencart 1.5.6.4/upload/catalog/controller/module/smaily_for_opencart.php
- opencart 1.5.6.4/upload/catalog/controller/smailyforopencart/cron_customers.php
- opencart 1.5.6.4/upload/catalog/controller/smailyforopencart/rss.php
- opencart 1.5.6.4/upload/catalog/language/english/module/smaily_for_opencart.php
- opencart 1.5.6.4/upload/catalog/model/smailyforopencart/helper.php
- opencart 1.5.6.4/upload/catalog/view/theme/default/template/module/smaily_for_opencart.tpl
- opencart 1.5.6.4/upload/catalog/view/theme/default/template/smailyforopencart/rss.tpl
- readme.md
> Smaily Opencart Module version 1.5.6.4

- opencart 1.5.6.4/upload/catalog/controller/smailyforopencart/cron_customers.php
- opencart 2.2.0.0/upload/catalog/controller/smailyforopencart/cron_customers.php
- opencart 2.2.0.0/upload/catalog/model/smailyforopencart/helper.php
- opencart 2.3.0.0 - 2.3.0.2/upload/catalog/controller/extension/smailyforopencart/cron_customers.php
- opencart 2.3.0.0 - 2.3.0.2/upload/catalog/model/extension/smailyforopencart/helper.php
- opencart 3.0.0.0 - 3.0.3.1/upload/catalog/controller/extension/smailyforopencart/cron_customers.php
- opencart 3.0.0.0 - 3.0.3.1/upload/catalog/model/extension/smailyforopencart/helper.php
Draft.
Needs testing for versions above 2.2
> Implement Customer Sync logic from 1.5 ver

- opencart 1.5.6.4/docker-compose.yml
- opencart 2.2.0.0/docker-compose.yml
- opencart 2.3.0.0 - 2.3.0.2/docker-compose.yml
- opencart 3.0.0.0 - 3.0.3.1/docker-compose.yml
> Add phpMyAdmin to docker-compose

- readme.md
Forgot to add `base_price` field to `readme.md`
> Add base price field to readme

- .gitattributes
- CHANGELOG.md
- install.xml
- upload/admin/controller/module/smaily_for_opencart.php
- upload/catalog/model/smailyforopencart/helper.php
Fixes customer synchronization cron not executing.
Fixes #35
> Fix customer cron not executing

- .gitattributes
Removes redundant `.gitattributes` file #47.
> Remove gitattributes

- CHANGELOG.md
- install.xml
- upload/admin/controller/extension/module/smaily_for_opencart.php
- upload/admin/language/en-gb/extension/module/smaily_for_opencart.php
- upload/admin/view/template/extension/module/smaily_for_opencart.tpl
This pull request adds a new button to the settings page to reset credentials.
As mentioned in #49, the module is now enabled on successful credentials verification.
> Feature reset credentials 2.3.x

- CHANGELOG.md
- install.xml
- upload/admin/controller/module/smaily_for_opencart.php
- upload/admin/language/en-gb/module/smaily_for_opencart.php
- upload/admin/view/template/module/smaily_for_opencart.tpl
Adds a reset credentials button to clear currently saved credentials.
Enables module on successful credentials validation as mentioned in #49
> Feature reset credentials 2.2.x

- CHANGELOG.md
- install.xml
- upload/admin/controller/extension/module/smaily_for_opencart.php
- upload/admin/language/en-gb/extension/module/smaily_for_opencart.php
- upload/admin/view/javascript/smailyforopencart/smaily_admin.js
- upload/admin/view/template/extension/module/smaily_for_opencart.twig
Adds reset credentials section and enables the module on successful validation #49
> Feature reset credentials 3.0.x

- CHANGELOG.md
- install.xml
- upload/admin/controller/module/smaily_for_opencart.php
> Fix valid credentials not accepted

- CHANGELOG.md
- upload/admin/controller/module/smaily_for_opencart.php
- upload/admin/view/template/module/smaily_for_opencart.tpl
> Display layout section after module validation

- upload/admin/controller/extension/module/smaily_for_opencart.php
- upload/admin/controller/extension/smailyforopencart/upgrade.php
- upload/catalog/controller/extension/smailyforopencart/order.php
- upload/catalog/model/extension/smailyforopencart/helper.php
> Reset abandoned cart when emptying cart

- upload/catalog/model/extension/smailyforopencart/helper.php
> Use last item addition time as cart abandoned time

- upload/admin/controller/module/smaily_for_opencart.php
- upload/admin/controller/smailyforopencart/upgrade.php
- upload/catalog/model/smailyforopencart/helper.php
> Add abandoned cart init time when activating

- upload/admin/controller/extension/module/smaily_for_opencart.php
- upload/admin/controller/extension/smailyforopencart/upgrade.php
- upload/catalog/controller/extension/smailyforopencart/order.php
- upload/catalog/model/extension/smailyforopencart/helper.php
> Hotfix/reset abandoned cart 2.3.x

- upload/catalog/model/extension/smailyforopencart/helper.php
> Hotfix/abandoned cart update time 2.3.x

- upload/admin/controller/extension/module/smaily_for_opencart.php
- upload/admin/controller/extension/smailyforopencart/upgrade.php
- upload/catalog/model/extension/smailyforopencart/helper.php
> Hotfix/abandoned cart init time 3.0.x

- upload/admin/controller/extension/module/smaily_for_opencart.php
- upload/admin/controller/extension/smailyforopencart/upgrade.php
- upload/catalog/model/extension/smailyforopencart/helper.php
> Hotfix/abandoned cart init time 2.3.x

- CHANGELOG.md
- install.xml
- upload/admin/controller/module/smaily_for_opencart.php
Version 1.3.2 for branch 2.2.x
> Version bump 1.3.2 for OpenCart 2.2.x

- CHANGELOG.md
Adding issue links to the changelog for easy access from the browser.
> Add issue links to changelog

- CHANGELOG.md
- install.xml
- upload/admin/controller/extension/module/smaily_for_opencart.php
Version bump to 1.3.2, added changelog
> Version 1.3.2 for OpenCart 2.3.x

- CHANGELOG.md
- install.xml
- upload/admin/controller/extension/module/smaily_for_opencart.php
Version 1.3.2, added changelog
> Version 1.3.2 for OpenCart3.0.x

- upload/admin/view/template/module/smaily_for_opencart.tpl
- upload/catalog/controller/smailyforopencart/cron_customers.php
> Unify use of first_name & last_name as field names

- upload/admin/view/template/extension/module/smaily_for_opencart.tpl
- upload/catalog/controller/extension/smailyforopencart/cron_customers.php
> Unify use of first_name and last_name field names

- upload/admin/view/template/extension/module/smaily_for_opencart.twig
- upload/catalog/controller/extension/smailyforopencart/cron_customers.php
> Unify use of first_name & last_name field names

- upload/catalog/controller/module/smaily_for_opencart.php
- upload/catalog/view/theme/default/template/module/smaily_for_opencart.tpl
> Add lang field to form

- CONTRIBUTING.md
Also remove all references to Wordpress.
> Improve phrasing of environment resetting section

- upload/admin/controller/extension/module/smaily_for_opencart.php
- upload/admin/language/en-gb/extension/module/smaily_for_opencart.php
- upload/admin/model/extension/smailyforopencart/admin.php
- upload/admin/view/javascript/smailyforopencart/smaily_admin.js
- upload/admin/view/template/extension/module/smaily_for_opencart.twig
- upload/admin/view/theme/default/stylesheet/smaily_oc.css
- upload/modman
> Add abandoned cart page

- upload/admin/controller/module/smaily_for_opencart.php
- upload/admin/language/en-gb/module/smaily_for_opencart.php
- upload/admin/model/smailyforopencart/admin.php
- upload/admin/view/stylesheet/smaily_oc.css
- upload/admin/view/template/module/smaily_for_opencart.tpl
- upload/modman
> Add abandoned cart status page

- upload/admin/controller/extension/module/smaily_for_opencart.php
- upload/admin/language/en-gb/extension/module/smaily_for_opencart.php
- upload/admin/model/extension/smailyforopencart/admin.php
- upload/admin/view/stylesheet/smaily_oc.css
- upload/admin/view/template/extension/module/smaily_for_opencart.tpl
- upload/modman
>  Add abandoned cart status page

- upload/admin/controller/extension/module/smaily_for_opencart.php
> Display module version

- .github/pull_request_template.md
as discussed in #130
tried to word it so distinctive, open to any suggestions
> Add reminder to update version in controller checklist 

- upload/admin/model/extension/smailyforopencart/admin.php
- upload/catalog/controller/extension/smailyforopencart/cron_cart.php
- upload/catalog/model/extension/smailyforopencart/helper.php
#124 
Currently adding invalid email to sent database to stop it from getting stuck.
> Fix cart cron getting stuck on invalid email

- upload/admin/controller/module/smaily_for_opencart.php
- upload/admin/language/en-gb/module/smaily_for_opencart.php
- upload/admin/model/smailyforopencart/admin.php
- upload/catalog/controller/smailyforopencart/cron_cart.php
- upload/catalog/controller/smailyforopencart/cron_customers.php
- upload/catalog/model/smailyforopencart/helper.php
- upload/modman
- upload/system/library/smailyforopencart/request.php
#124 
refactors and simplifies code used for making requests against Smaily's API.
OpenCart 2.2.x
> Move cURL calls to a seperate Request library

- upload/catalog/model/smailyforopencart/helper.php
> Unsubscribing in chunks doesn't work in chunks

- upload/admin/model/extension/smailyforopencart/admin.php
same formatting error was in #140 if it seems similar to you
> Add missing identation

- upload/admin/controller/extension/module/smaily_for_opencart.php
> Fix/rss limit value error 2.3.x

- upload/admin/controller/module/smaily_for_opencart.php
> Fix/rss limit value error 2.2.x

- upload/admin/controller/extension/module/smaily_for_opencart.php
> Fix/rss limit value error 3.0.x

- CHANGELOG.md
- upload/admin/controller/module/smaily_for_opencart.php
changes necessary to release 1.3.0 for OpenCart 1.5.x
> 1.3.0 for 1.5.x release checklist changes

- CHANGELOG.md
- install.xml
- upload/admin/controller/extension/module/smaily_for_opencart.php
changes required to release 1.5.0 for OC 2.3.x
> 1.5.0 for 2.3.x release checklist changes

- CHANGELOG.md
- install.xml
- upload/admin/controller/extension/module/smaily_for_opencart.php
changes required to release 1.5.0 for OC 3.0.x
> 1.5.0 for 3.0.x release checklist changes

- CHANGELOG.md
- install.xml
- upload/admin/controller/module/smaily_for_opencart.php
changes necessary to release 1.5.0 for OpenCart 2.2.x
> 1.5.0 for 2.2.x release checklist changes

- upload/catalog/view/theme/default/template/extension/smailyforopencart/rss.twig
> RSS image link should be supplied by URL attribute

- CHANGELOG.md
- install.xml
- upload/admin/controller/extension/module/smaily_for_opencart.php
**1.5.2 for 3.0.x release checklist**
> 1.5.2 for 3.0.x release checklist changes

- CHANGELOG.md
- install.xml
- upload/admin/controller/extension/module/smaily_for_opencart.php
> 1.5.2 for 2.3.x release checklist change

- CHANGELOG.md
- install.xml
- upload/admin/controller/module/smaily_for_opencart.php
> 1.5.2 for 2.2.x release checklist change

- CHANGELOG.md
- install.xml
- upload/admin/controller/module/smaily_for_opencart.php
**Version changelog**
A list of changes regarding the next version release:
- Fix validation error not showing if RSS product limit higher than 250 - [[#195](https://github.com/sendsmaily/smaily-opencart-module/pull/195)]
**Release checklist**
**After PR merge**
> Release 1.5.2 for 2.2.x
